AllCops: 
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Gemspec/DeprecatedAttributeAssignment: # new in 1.30 
  Enabled: true 
Gemspec/RequireMFA: # new in 1.23 
  Enabled: true 
Layout/LineContinuationLeadingSpace: # new in 1.31 
  Enabled: true 
Layout/LineContinuationSpacing: # new in 1.31 
  Enabled: true 
Layout/LineEndStringConcatenationIndentation: # new in 1.18 
  Enabled: true 
Layout/SpaceBeforeBrackets: # new in 1.7 
  Enabled: true 
Lint/AmbiguousAssignment: # new in 1.7 
  Enabled: true 
Lint/AmbiguousOperatorPrecedence: # new in 1.21 
  Enabled: true 
Lint/AmbiguousRange: # new in 1.19 
  Enabled: true 
Lint/ConstantOverwrittenInRescue: # new in 1.31 
  Enabled: true 
Lint/DeprecatedConstants: # new in 1.8 
  Enabled: true 
Lint/DuplicateBranch: # new in 1.3 
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37 
  Enabled: true 
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1 
  Enabled: true 
Lint/EmptyBlock: # new in 1.1 
  Enabled: true 
Lint/EmptyClass: # new in 1.3 
  Enabled: true 
Lint/EmptyInPattern: # new in 1.16 
  Enabled: true 
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21 
  Enabled: true 
Lint/LambdaWithoutLiteralBlock: # new in 1.8 
  Enabled: true 
Lint/NoReturnInBeginEndBlocks: # new in 1.2 
  Enabled: true 
Lint/NonAtomicFileOperation: # new in 1.31 
  Enabled: true 
Lint/NumberedParameterAssignment: # new in 1.9 
  Enabled: true 
Lint/OrAssignmentToConstant: # new in 1.9 
  Enabled: true 
Lint/RedundantDirGlobSort: # new in 1.8 
  Enabled: true 
Lint/RefinementImportMethods: 
  Enabled: true 